{{- if .Values.httpproxy.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "proglog.labels" . | nindent 4 }}
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: {{ .Values.hostname }}
  routes:
    - conditions:
        - prefix: {{ .Values.externalPath }}
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
      services:
        - name: {{ include "proglog.fullname" . }}
          port: {{ .Values.rpcPort }}
{{- if .Values.httpproxy.enabled }}
